FROM node:${VERSION_NODE}

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@^${VERSION_RSC} -g --silent

COPY . ./

CMD ["npm", "start"]
